# Configuration for Alacritty, the GPU enhanced terminal emulator.
env:
  WINIT_X11_SCALE_FACTOR: "1"

window:
  decorations: none

scrolling:
  history: 100000

# Font configuration
font:
  normal:
    family: Hack
  bold:
    family: Hack
    style: Bold
  italic:
    family: Hack
    style: Italic
  size: 10.0

colors:
  primary:
    background: '0x282828'
    foreground: '0xdbdbb2'

background_opacity: 0.9

key_bindings:
  - { key: N,        mods: Command,    action: SpawnNewInstance    }

# vim: set sw=2 ts=2 et:
